#!/bin/bash
if ! [ hash thunter 2>/dev/null ]; then
    exit 0
fi
branch_name=$(git rev-parse --abbrev-ref HEAD)
is_branch_switch=$3
if [[ "$is_branch_switch" == "1" ]]; then
    if [[ "$branch_name" == "main" || "$branch_name" == "master" || "$branch_name" == "dev" || "$branch_name" == "HEAD" ]]; then
        thunter stop
    else
        thunter workon --create "$branch_name" < /dev/tty
    fi
fi
